# Generated by Django 4.2.23 on 2025-07-25 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=150)),
                ('about', models.TextField()),
                ('profile_image', models.ImageField(default='default.jpg', upload_to='profile_images/')),
                ('cv', models.FileField(blank=True, null=True, upload_to='cvs/')),
            ],
        ),
    ]
