# Generated by Django 4.2.23 on 2025-07-25 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hero_background_image',
            field=models.ImageField(blank=True, null=True, upload_to='hero/'),
        ),
    ]
